# -*- coding: utf-8 -*-
"""Dynamic_heatmap_with_alert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LN0f6o_rXrG4nEmOD4A30lEdKXxoCC7H
"""

from google.colab import drive
drive.mount('/content/drive')

pip install ultralytics

pip install adafruit-io

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from ultralytics import YOLO
from google.colab.patches import cv2_imshow
import seaborn as sns
from Adafruit_IO import Client, Feed, RequestError

FRAMES_FOLDER = '/content/drive/MyDrive/Crowd_detection/vidf1_33_000/'  # <<< CHANGE THIS
CROWD_THRESHOLD = 13
CROWD_THRESHOLD_1 = 17
MODEL_TYPE = 'yolov8n.pt'
OUTPUT_VIDEO = 'crowd_detection_output.avi'
FRAME_RATE = 10  # FPS
count_frame = 0
HEATMAP_UPDATE_INTERVAL = 25  # Update heatmap every 50 frames
print(FRAMES_FOLDER)

# Replace with your actual credentials
ADAFRUIT_IO_USERNAME = "Anamit"
ADAFRUIT_IO_KEY = "aio_xxxxxxxxxxxxxxx"

aio = Client(ADAFRUIT_IO_USERNAME, ADAFRUIT_IO_KEY)
# ✅ Safe feed creation: if it doesn't exist, create it
try:
    alert = aio.feeds('crowd_alert')
except RequestError:
    print("[INFO] Feed 'crowd_alert' not found. Creating it now...")
    feed = Feed(name='crowd_alert')
    alert = aio.create_feed(feed)
def send_adafruit_alert(count):
  print("Inside function")
  # aio.send('crowd_alert', count)
  aio.send(alert.key, count)
  print(f"[INFO] Alert sent to Adafruit IO: {count} people")

print("[INFO] Loading YOLO model...")
model = YOLO(MODEL_TYPE)

frame_files = sorted([os.path.join(FRAMES_FOLDER, f) for f in os.listdir(FRAMES_FOLDER) if f.endswith('.png') or f.endswith('.jpg')])

if not frame_files:
    print("[ERROR] No frames found in the folder.")
    exit()

print(f"[INFO] {len(frame_files)} frames found. Starting processing... Press 'q' to quit.")

# ================================
# Initialize Video Writer
# ================================
first_frame = cv2.imread(frame_files[0])
height, width, _ = first_frame.shape
fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter(OUTPUT_VIDEO, fourcc, FRAME_RATE, (width, height))

# Load heatmap points
heatmap_points = []

# ================================
# Real-time detection loop
# ================================
for frame_path in frame_files:
    frame = cv2.imread(frame_path)

    results = model(frame)
    detections = results[0].boxes

    person_count = len(detections)

    # Collect center points for heatmap
    for box in detections.xyxy:
        x1, y1, x2, y2 = box[:4]
        center_x = int((x1 + x2) / 2)
        center_y = int((y1 + y2) / 2)
        heatmap_points.append((center_x, center_y))

    # Annotated frame
    annotated_frame = results[0].plot()

    # Threshold alert
    if person_count > CROWD_THRESHOLD and person_count <= CROWD_THRESHOLD_1:
        print(f"[ALERT] Crowd threshold exceeded! People detected: {person_count}")
    elif person_count > CROWD_THRESHOLD_1:
        print(f"[EMERGENCY!!] Stop Entry points. People detected: {person_count}")
        send_adafruit_alert(person_count)

    # Overlay total count
    cv2.putText(
        annotated_frame,
        f"Total Persons: {person_count}",
        (10, 30),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.3,
        (0, 255, 0),
        1,
        cv2.LINE_AA
    )

    # Show frame
    # Convert BGR (OpenCV) to RGB (Matplotlib)
    frame_rgb = cv2.cvtColor(annotated_frame, cv2.COLOR_BGR2RGB)

    plt.imshow(frame_rgb)
    plt.axis('off')
    plt.show()

    count_frame += 1
    # Every N frames, update and show heatmap
    if count_frame % HEATMAP_UPDATE_INTERVAL == 0:
      print("[INFO] Generating heatmap...")

      np.save('heatmap_points.npy', heatmap_points)

      heatmap_array = np.array(heatmap_points)
      x_coords = heatmap_array[:, 0]
      y_coords = heatmap_array[:, 1]


      print("[INFO] Building 2D people count grid...")

      # Define grid resolution
      num_bins = 50

      # Create 2D histogram
      H, xedges, yedges = np.histogram2d(x_coords, y_coords, bins=num_bins)

      print("[INFO] Plotting people count heatmap...")

      plt.figure(figsize=(14, 10))

      ax = sns.heatmap(
          H.T,  # Transpose H because matplotlib expects (Y, X)
          cmap='Reds',
          cbar=True,
          linewidths=0.5,
          annot=True,
          fmt=".0f",  # no decimals, only integer counts
          annot_kws={"size": 7}
      )


    # Save frame to video
    out.write(annotated_frame)

